#!/usr/bin/env bash
# script that will display information about subdomains

domain_info () {
	line=$(dig "$2"."$1" | grep -iA1 "answer section:" | awk '{print $4" "$5}' | tr '\n' ' ')
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [[ "$#" == 1 ]]
then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [[ "$#" == 2 ]]
then
	domain_info "$1" "$2"
fi
