#!/usr/bin/env bash
#a script that installs nginx on my web server

sudo su root - &&\
apt update -y &&\
apt install nginx -y &&\
echo 'Hello World!' > /var/www/html/index.nginx-debian.html ;\
sudo service nginx start
