#!/usr/bin/env bash
#a script that installs nginx on my web server

sudo apt update -y
sudo apt install nginx -y
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
