#!/usr/bin/env bash
#this script configures the nginx server on my remote server to redirect
#requests to /redirect_me endpoints to youtube website

sudo su root - &&\
sudo apt-get -y update &&\
sudo apt-get -y install nginx &&\
echo "Hello World" | sudo tee /var/www/html/index ;\
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default ;\
sudo service nginx restart
