#!/usr/bin/env bash
# this module spins up a new server configuration related to the server used in the previous project

sudo su root -
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/my_404.html
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$host;
	location / {
		try_files \$uri \$uri/ =404;
	}
	rewrite ^/redirect_me https://youtube.com permanent;
	error_page 404 /my_404.html;
	location = /my_404.html {
		internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
