#!/usr/bin/env bash
# this script Configures Nginx so that its HTTP response contains
# a custom header

sudo su root -
haproxy_config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 36052-web-01 54.237.91.177:80 check
    server 36052-web-02 18.210.17.238:80 check
"
apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$haproxy_config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
