#!/usr/bin/env bash
# A script that pings an IP address passed as an argument 5x
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
if [ "$#" -ge 1 ]
then
		ping -c 5 "$1"
else
		echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
