#!/usr/bin/env bash
# changes the default listening port in nginx
sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:8080 default_server;/listen [::]:80 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/8080/80' /etc/nginx/sites-enabled/default
sudo service nginx restart
