#!/usr/bin/env bash
#this ia a script that prints some strings at some iterations in a loop
count=0
while [[ "$count" -lt 20 ]];
do
	echo "$((count + 1))"
	case "$count" in
		3)
		echo "bad luck from China"
		;;
		8)
		echo "bad luck from Japan"
		;;
		16)
		echo "bad luck from Italy"
	esac
	((count++))
done
