#!/usr/bin/env bash
#this ia a script that prints some strings at some iterations in a loop
count=0
while [[ "$count" -lt 20 ]];
do
	echo "$((count + 1))"
	if [[ "$count" -eq 3 ]];
	then
		echo "bad luck from China"
	elif [[ "$count" -eq 8 ]];
	then
		echo "bad luck from Japan"
	elif [[ "$count" -eq 16 ]];
	then
		echo "back luck from Italy"
	fi
	((count++))
done
