#!/usr/bin/env bash
#this ia a script that list non-hidden files in a directory in a specified format
REGEX_PATTERN="^\.\/\w+-(.*)"
REGEX_PATTERN2="^\.\/(.*)"
for file in "."/*;
do
	if [[ "$file" =~ $REGEX_PATTERN ]];
	then
		result="${BASH_REMATCH[1]}"
		echo "$result"
	else
		if [[ "$file" =~ $REGEX_PATTERN2 ]];
		then
			echo "${BASH_REMATCH[1]}"
		fi
	fi
done
