#!/usr/bin/env bash
#this ia a script that list non-hidden files in a directory in a specified format
REGEX_PATTERN="^\.\/\w+-(.*)"
for file in "."/*;
do
	if [[ "$file" =~ $REGEX_PATTERN ]];
	then
		result="${BASH_REMATCH[1]}"
		echo "$result"
	fi
done
