#!/usr/bin/env bash
#this ia a script that prints some strings based on some attributes of the currently listed files
filename="school"
if [[ -e "$filename" ]];
then
	echo "$filename file exists"
	if [[ ! -s "$filename" ]];
	then
		echo "$filename file is empty"
	else
		echo "$filename file is not empty"
	fi
	if [[ -f "$filename" ]];
	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
