#!/usr/bin/env bash
# this script runs the nginx service as the nginx user

sudo adduser --no-create-home --disabled-login --disabled-password --group nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo service nginx restart
